### ISSUE TITLE
Automatic video rendering of tours

### ISSUE THREAD

**Issue by patudom** [WorldWideTelescope/wwt-windows-client#9] opened 2015-06-15 18:49 UTC
possibly via Azure, by turning pngs into mov using ffmpeg—or better, local video export

From Alyssa Goodman email on 4/20 after conversation at Northwestern University with various OpenWWT constituents.

**Comment by doctorspaceman** [comment] 2015-10-12 20:59
This is a duplicate of Issue #29. Closing this.

**Closed by doctorspaceman** 2015-10-12 20:59 UTC
