### ISSUE TITLE
stopping tour crashes all machines in cluster

### ISSUE THREAD

**Issue by nell-byler** [WorldWideTelescope/wwt-windows-client#48] opened 2016-01-13 05:50 UTC
When you stop the playback of a tour with version 5.2.9.1 running on cluster, all the machines in the cluster crash.

**Comment by cecilia-donnelly** [comment] 2016-01-13 15:24
@astrojonathan and @nell-byler, this looks very similar to #47.  Is it the same bug?  (I think maybe you two talked about it and then each of you opened an issue.)

Thanks for the report, Nell, and the quick fix of #47, Jonathan!

**Comment by astrojonathan** [comment] 2016-01-13 15:49
Fixed. Duplicate of #47.

**Closed by astrojonathan** 2016-01-13 15:49 UTC
