### ISSUE TITLE
Lighting not working for user-added layers on bodies

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-windows-client#70] opened 2016-06-09 20:09 UTC
When I add a layer from a new TOAST tile set, the body no longer shows shadows when "Lighting and Shadows" is selected in the layer manager.

**Comment by astrodavid** [comment] 2019-01-05 04:58
Duplicate of #115, fixed

**Closed by astrodavid** 2019-01-05 04:58 UTC
Labels: enhancement
